export * from './About';
export * from './Faq';
export * from './HowItWorks';
export * from './legal';
export * from './OurServices';
export * from './Pickup';
export * from './profile';
export * from './UpcomingOrders';
export * from './welcome';
