export const getProfile = () => ({
  id: 1,
  email: 'username@example.com',
  subscription: 'payc',
  mainPhone: '+11234564897',
  firstName: 'FirstName',
  lastName: 'LastName',
  balance: 19900,
  dollarBalance: 199.0,
  stripeId: 'cus_IDEPCAjgKy6vVR',
  fabricSoftener: false,
  fixTears: false,
  isAutoBilling: false,
  mainCard: 1,
  mainAddress: 1,
  mainBillingAddress: 1,
});

export const getAddresses = () => [
  {
    id: 12,
    zipCode: '95014',
    title: 'Main',
    addressLine1: '1 Apple Park Way, Cupertino, CA, USA',
    addressLine2: '',
    hasDoorman: false,
  },
  {
    id: 11,
    zipCode: '95014',
    title: 'Main',
    addressLine1: '1 Apple Park Way, Cupertino, CA, USA',
    addressLine2: '',
    hasDoorman: false,
  },
];

export const getAddress = () => ({
  id: 11,
  zipCode: '95014',
  title: 'Main',
  addressLine1: '1 Apple Park Way, Cupertino, CA, USA',
  addressLine2: '',
  hasDoorman: false,
});

export const getPackages = () => [
  {
    id: 1,
    dollarPrice: 0.0,
    price: 0,
    dryClean: 0,
    laundry: 0,
    alterations: 0,
    washFold: 0,
    deliveryFreeFrom: 4900,
    hasDelivery: false,
    hasWelcomeBox: false,
    hasSeasonalGarment: false,
    hasCreditBack: false,
    isMostPopular: false,
    name: 'payc',
    description: 'Pay as You Clean',
  },
  {
    id: 2,
    dollarPrice: 199.0,
    price: 19900,
    dryClean: 10,
    laundry: 10,
    alterations: 10,
    washFold: 10,
    deliveryFreeFrom: 3900,
    hasDelivery: true,
    hasWelcomeBox: true,
    hasSeasonalGarment: false,
    hasCreditBack: false,
    isMostPopular: false,
    name: 'gold',
    description: 'Pre Pay Credit',
  },
  {
    id: 3,
    dollarPrice: 299.0,
    price: 29900,
    dryClean: 20,
    laundry: 20,
    alterations: 20,
    washFold: 20,
    deliveryFreeFrom: 3900,
    hasDelivery: true,
    hasWelcomeBox: true,
    hasSeasonalGarment: true,
    hasCreditBack: true,
    isMostPopular: true,
    name: 'platinum',
    description: 'Pre Pay Credit',
  },
];

export const getCards = () => [
  {
    id: 1,
    stripeId: 'pm_1HloKWEIZcTcPHNvLkm5gatJ',
    last: '4242',
    expirationMonth: 4,
    expirationYear: 2024,
    isActive: true,
  },
];
