/* tslint:disable */
/* eslint-disable */
/**
 * WashMix
 * WashMix REST API
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Client
 */
export interface Client {
    /**
     * 
     * @type {number}
     * @memberof Client
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof Client
     */
    readonly mainPhone?: string;
    /**
     * 
     * @type {string}
     * @memberof Client
     */
    readonly firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof Client
     */

    readonly client_numbers?: string;
    /**
     * 
     * @type {string}
     * @memberof Delivery
     */

    readonly lastName?: string;
}

export function ClientFromJSON(json: any): Client {
    return ClientFromJSONTyped(json, false);
}

export function ClientFromJSONTyped(json: any, ignoreDiscriminator: boolean): Client {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'mainPhone': !exists(json, 'main_phone') ? undefined : json['main_phone'],
        'firstName': !exists(json, 'first_name') ? undefined : json['first_name'],
        'lastName': !exists(json, 'last_name') ? undefined : json['last_name'],
        'client_numbers': !exists(json, 'client_numbers') ? undefined : json['client_numbers'],

    };
}

export function ClientToJSON(value?: Client | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}


