/* tslint:disable */
/* eslint-disable */
/**
 * WashMix
 * WashMix REST API
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrderApplyCouponResponse
 */
export interface OrderApplyCouponResponse {
    /**
     * 
     * @type {number}
     * @memberof OrderApplyCouponResponse
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof OrderApplyCouponResponse
     */
    readonly subscription?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderApplyCouponResponse
     */
    readonly coupon?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderApplyCouponResponse
     */
    readonly amount?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderApplyCouponResponse
     */
    readonly dollarAmount?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderApplyCouponResponse
     */
    readonly discount?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderApplyCouponResponse
     */
    readonly dollarDiscount?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderApplyCouponResponse
     */
    readonly amountWithDiscount?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderApplyCouponResponse
     */
    readonly dollarAmountWithDiscount?: string;
}

export function OrderApplyCouponResponseFromJSON(json: any): OrderApplyCouponResponse {
    return OrderApplyCouponResponseFromJSONTyped(json, false);
}

export function OrderApplyCouponResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderApplyCouponResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'subscription': !exists(json, 'subscription') ? undefined : json['subscription'],
        'coupon': !exists(json, 'coupon') ? undefined : json['coupon'],
        'amount': !exists(json, 'amount') ? undefined : json['amount'],
        'dollarAmount': !exists(json, 'dollar_amount') ? undefined : json['dollar_amount'],
        'discount': !exists(json, 'discount') ? undefined : json['discount'],
        'dollarDiscount': !exists(json, 'dollar_discount') ? undefined : json['dollar_discount'],
        'amountWithDiscount': !exists(json, 'amount_with_discount') ? undefined : json['amount_with_discount'],
        'dollarAmountWithDiscount': !exists(json, 'dollar_amount_with_discount') ? undefined : json['dollar_amount_with_discount'],
    };
}

export function OrderApplyCouponResponseToJSON(value?: OrderApplyCouponResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}


