/* tslint:disable */
/* eslint-disable */
/**
 * WashMix
 * WashMix REST API
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrderRemoveCoupon
 */
export interface OrderRemoveCoupon {
    /**
     * 
     * @type {string}
     * @memberof OrderRemoveCoupon
     */
    order: string;
}

export function OrderRemoveCouponFromJSON(json: any): OrderRemoveCoupon {
    return OrderRemoveCouponFromJSONTyped(json, false);
}

export function OrderRemoveCouponFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderRemoveCoupon {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'order': json['order'],
    };
}

export function OrderRemoveCouponToJSON(value?: OrderRemoveCoupon | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'order': value.order,
    };
}


