/* tslint:disable */
/* eslint-disable */
/**
 * WashMix
 * WashMix REST API
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Package
 */
export interface Package {
    /**
     * 
     * @type {number}
     * @memberof Package
     */
    readonly id?: number;
    /**
     * 
     * @type {number}
     * @memberof Package
     */
    dollarPrice: number;
    /**
     * 
     * @type {number}
     * @memberof Package
     */
    price?: number;
    /**
     * in percents
     * @type {number}
     * @memberof Package
     */
    dryClean: number;
    /**
     * in percents
     * @type {number}
     * @memberof Package
     */
    laundry: number;
    /**
     * in percents
     * @type {number}
     * @memberof Package
     */
    alterations: number;
    /**
     * in percents
     * @type {number}
     * @memberof Package
     */
    washFold: number;
    /**
     * 
     * @type {number}
     * @memberof Package
     */
    deliveryFreeFrom: number;
    /**
     * 
     * @type {boolean}
     * @memberof Package
     */
    hasDelivery: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Package
     */
    hasWelcomeBox: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Package
     */
    hasSeasonalGarment: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Package
     */
    hasCreditBack: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Package
     */
    isMostPopular?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Package
     */
    name: PackageNameEnum;
    /**
     * 
     * @type {string}
     * @memberof Package
     */
    description?: string;
}

export function PackageFromJSON(json: any): Package {
    return PackageFromJSONTyped(json, false);
}

export function PackageFromJSONTyped(json: any, ignoreDiscriminator: boolean): Package {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'dollarPrice': json['dollar_price'],
        'price': !exists(json, 'price') ? undefined : json['price'],
        'dryClean': json['dry_clean'],
        'laundry': json['laundry'],
        'alterations': json['alterations'],
        'washFold': json['wash_fold'],
        'deliveryFreeFrom': json['delivery_free_from'],
        'hasDelivery': json['has_delivery'],
        'hasWelcomeBox': json['has_welcome_box'],
        'hasSeasonalGarment': json['has_seasonal_garment'],
        'hasCreditBack': json['has_credit_back'],
        'isMostPopular': !exists(json, 'is_most_popular') ? undefined : json['is_most_popular'],
        'name': json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
    };
}

export function PackageToJSON(value?: Package | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'dollar_price': value.dollarPrice,
        'price': value.price,
        'dry_clean': value.dryClean,
        'laundry': value.laundry,
        'alterations': value.alterations,
        'wash_fold': value.washFold,
        'delivery_free_from': value.deliveryFreeFrom,
        'has_delivery': value.hasDelivery,
        'has_welcome_box': value.hasWelcomeBox,
        'has_seasonal_garment': value.hasSeasonalGarment,
        'has_credit_back': value.hasCreditBack,
        'is_most_popular': value.isMostPopular,
        'name': value.name,
        'description': value.description,
    };
}

/**
* @export
* @enum {string}
*/
export enum PackageNameEnum {
    Payc = 'payc',
    Gold = 'gold',
    Platinum = 'platinum'
}


