/* tslint:disable */
/* eslint-disable */
/**
 * WashMix
 * WashMix REST API
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface POSBasketClear
 */
export interface POSBasketClear {
    /**
     * 
     * @type {number}
     * @memberof POSBasketClear
     */
    order: number;
}

export function POSBasketClearFromJSON(json: any): POSBasketClear {
    return POSBasketClearFromJSONTyped(json, false);
}

export function POSBasketClearFromJSONTyped(json: any, ignoreDiscriminator: boolean): POSBasketClear {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'order': json['order'],
    };
}

export function POSBasketClearToJSON(value?: POSBasketClear | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'order': value.order,
    };
}


