/* tslint:disable */
/* eslint-disable */
/**
 * WashMix
 * WashMix REST API
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface POSBasketChangeItem
 */
export interface POSBasketChangeItem {
    /**
     * 
     * @type {number}
     * @memberof POSBasketChangeItem
     */
    price: number;
    /**
     * 
     * @type {number}
     * @memberof POSBasketChangeItem
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof POSBasketChangeItem
     */
    action: POSBasketChangeItemActionEnum;
    /**
     * 
     * @type {number}
     * @memberof POSBasketChangeItem
     */
    order: number;
}

export function POSBasketChangeItemFromJSON(json: any): POSBasketChangeItem {
    return POSBasketChangeItemFromJSONTyped(json, false);
}

export function POSBasketChangeItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): POSBasketChangeItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'price': json['price'],
        'count': json['count'],
        'action': json['action'],
        'order': json['order'],
    };
}

export function POSBasketChangeItemToJSON(value?: POSBasketChangeItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'price': value.price,
        'count': value.count,
        'action': value.action,
        'order': value.order,
    };
}

/**
* @export
* @enum {string}
*/
export enum POSBasketChangeItemActionEnum {
    Add = 'add',
    Remove = 'remove'
}


