/* tslint:disable */
/* eslint-disable */
/**
 * WashMix
 * WashMix REST API
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    POSExtraItem,
    POSExtraItemFromJSON,
    POSExtraItemFromJSONTyped,
    POSExtraItemToJSON,
} from './';

/**
 * 
 * @export
 * @interface POSBasketSetExtraItems
 */
export interface POSBasketSetExtraItems {
    /**
     * 
     * @type {Array<POSExtraItem>}
     * @memberof POSBasketSetExtraItems
     */
    extraItems: Array<POSExtraItem>;
    /**
     * 
     * @type {number}
     * @memberof POSBasketSetExtraItems
     */
    order: number;
}

export function POSBasketSetExtraItemsFromJSON(json: any): POSBasketSetExtraItems {
    return POSBasketSetExtraItemsFromJSONTyped(json, false);
}

export function POSBasketSetExtraItemsFromJSONTyped(json: any, ignoreDiscriminator: boolean): POSBasketSetExtraItems {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'extraItems': ((json['extra_items'] as Array<any>).map(POSExtraItemFromJSON)),
        'order': json['order'],
    };
}

export function POSBasketSetExtraItemsToJSON(value?: POSBasketSetExtraItems | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'extra_items': ((value.extraItems as Array<any>).map(POSExtraItemToJSON)),
        'order': value.order,
    };
}


