/* tslint:disable */
/* eslint-disable */
/**
 * WashMix
 * WashMix REST API
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface POSCoupon
 */
export interface POSCoupon {
    /**
     * 
     * @type {number}
     * @memberof POSCoupon
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof POSCoupon
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof POSCoupon
     */
    description?: string;
}

export function POSCouponFromJSON(json: any): POSCoupon {
    return POSCouponFromJSONTyped(json, false);
}

export function POSCouponFromJSONTyped(json: any, ignoreDiscriminator: boolean): POSCoupon {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'code': json['code'],
        'description': !exists(json, 'description') ? undefined : json['description'],
    };
}

export function POSCouponToJSON(value?: POSCoupon | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'description': value.description,
    };
}


