/* tslint:disable */
/* eslint-disable */
/**
 * WashMix
 * WashMix REST API
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface POSOrderApplyCoupon
 */
export interface POSOrderApplyCoupon {
    /**
     * 
     * @type {string}
     * @memberof POSOrderApplyCoupon
     */
    coupon: string;
    /**
     * 
     * @type {number}
     * @memberof POSOrderApplyCoupon
     */
    order: number;
}

export function POSOrderApplyCouponFromJSON(json: any): POSOrderApplyCoupon {
    return POSOrderApplyCouponFromJSONTyped(json, false);
}

export function POSOrderApplyCouponFromJSONTyped(json: any, ignoreDiscriminator: boolean): POSOrderApplyCoupon {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'coupon': json['coupon'],
        'order': json['order'],
    };
}

export function POSOrderApplyCouponToJSON(value?: POSOrderApplyCoupon | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'coupon': value.coupon,
        'order': value.order,
    };
}


