/* tslint:disable */
/* eslint-disable */
/**
 * WashMix
 * WashMix REST API
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface POSOrderPrepare
 */
export interface POSOrderPrepare {
    /**
     * 
     * @type {number}
     * @memberof POSOrderPrepare
     */
    client: number;
    /**
     * 
     * @type {number}
     * @memberof POSOrderPrepare
     */
    request: number;
}

export function POSOrderPrepareFromJSON(json: any): POSOrderPrepare {
    return POSOrderPrepareFromJSONTyped(json, false);
}

export function POSOrderPrepareFromJSONTyped(json: any, ignoreDiscriminator: boolean): POSOrderPrepare {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'client': json['client'],
        'request': json['request'],
    };
}

export function POSOrderPrepareToJSON(value?: POSOrderPrepare | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'client': value.client,
        'request': value.request,
    };
}


