/* tslint:disable */
/* eslint-disable */
/**
 * WashMix
 * WashMix REST API
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    POSOrderPrepareAddressResponse,
    POSOrderPrepareAddressResponseFromJSON,
    POSOrderPrepareAddressResponseFromJSONTyped,
    POSOrderPrepareAddressResponseToJSON,
} from './';

/**
 * 
 * @export
 * @interface POSOrderPrepareRequestResponse
 */
export interface POSOrderPrepareRequestResponse {
    /**
     * 
     * @type {number}
     * @memberof POSOrderPrepareRequestResponse
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof POSOrderPrepareRequestResponse
     */
    comment?: string;
    /**
     * 
     * @type {boolean}
     * @memberof POSOrderPrepareRequestResponse
     */
    isRush?: boolean;
    /**
     * 
     * @type {POSOrderPrepareAddressResponse}
     * @memberof POSOrderPrepareRequestResponse
     */
    address: POSOrderPrepareAddressResponse;
}

export function POSOrderPrepareRequestResponseFromJSON(json: any): POSOrderPrepareRequestResponse {
    return POSOrderPrepareRequestResponseFromJSONTyped(json, false);
}

export function POSOrderPrepareRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): POSOrderPrepareRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'comment': !exists(json, 'comment') ? undefined : json['comment'],
        'isRush': !exists(json, 'is_rush') ? undefined : json['is_rush'],
        'address': POSOrderPrepareAddressResponseFromJSON(json['address']),
    };
}

export function POSOrderPrepareRequestResponseToJSON(value?: POSOrderPrepareRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'comment': value.comment,
        'is_rush': value.isRush,
        'address': POSOrderPrepareAddressResponseToJSON(value.address),
    };
}


