/* tslint:disable */
/* eslint-disable */
/**
 * WashMix
 * WashMix REST API
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface POSOrderAlreadyFormedResponse
 */
export interface POSOrderAlreadyFormedResponse {
    /**
     * 
     * @type {boolean}
     * @memberof POSOrderAlreadyFormedResponse
     */
    formed: boolean;
    /**
     * 
     * @type {string}
     * @memberof POSOrderAlreadyFormedResponse
     */
    readonly order?: string | null;
}

export function POSOrderAlreadyFormedResponseFromJSON(json: any): POSOrderAlreadyFormedResponse {
    return POSOrderAlreadyFormedResponseFromJSONTyped(json, false);
}

export function POSOrderAlreadyFormedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): POSOrderAlreadyFormedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'formed': json['formed'],
        'order': !exists(json, 'order') ? undefined : json['order'],
    };
}

export function POSOrderAlreadyFormedResponseToJSON(value?: POSOrderAlreadyFormedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'formed': value.formed,
    };
}


