/* tslint:disable */
/* eslint-disable */
/**
 * WashMix
 * WashMix REST API
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface POSOrderCheckout
 */
export interface POSOrderCheckout {
    /**
     * 
     * @type {number}
     * @memberof POSOrderCheckout
     */
    order: number;
}

export function POSOrderCheckoutFromJSON(json: any): POSOrderCheckout {
    return POSOrderCheckoutFromJSONTyped(json, false);
}

export function POSOrderCheckoutFromJSONTyped(json: any, ignoreDiscriminator: boolean): POSOrderCheckout {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'order': json['order'],
    };
}

export function POSOrderCheckoutToJSON(value?: POSOrderCheckout | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'order': value.order,
    };
}


