/* tslint:disable */
/* eslint-disable */
/**
 * WashMix
 * WashMix REST API
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface POSOrderRemoveCoupon
 */
export interface POSOrderRemoveCoupon {
    /**
     * 
     * @type {number}
     * @memberof POSOrderRemoveCoupon
     */
    order: number;
}

export function POSOrderRemoveCouponFromJSON(json: any): POSOrderRemoveCoupon {
    return POSOrderRemoveCouponFromJSONTyped(json, false);
}

export function POSOrderRemoveCouponFromJSONTyped(json: any, ignoreDiscriminator: boolean): POSOrderRemoveCoupon {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'order': json['order'],
    };
}

export function POSOrderRemoveCouponToJSON(value?: POSOrderRemoveCoupon | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'order': value.order,
    };
}


