/* tslint:disable */
/* eslint-disable */
/**
 * WashMix
 * WashMix REST API
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    POSOrderPrepareClientResponse,
    POSOrderPrepareClientResponseFromJSON,
    POSOrderPrepareClientResponseFromJSONTyped,
    POSOrderPrepareClientResponseToJSON,
    POSOrderPrepareRequestResponse,
    POSOrderPrepareRequestResponseFromJSON,
    POSOrderPrepareRequestResponseFromJSONTyped,
    POSOrderPrepareRequestResponseToJSON,
} from './';

/**
 * 
 * @export
 * @interface POSOrderPrepareResponse
 */
export interface POSOrderPrepareResponse {
    /**
     * 
     * @type {number}
     * @memberof POSOrderPrepareResponse
     */
    readonly id?: number;
    /**
     * 
     * @type {POSOrderPrepareClientResponse}
     * @memberof POSOrderPrepareResponse
     */
    client: POSOrderPrepareClientResponse;
    /**
     * 
     * @type {POSOrderPrepareRequestResponse}
     * @memberof POSOrderPrepareResponse
     */
    request: POSOrderPrepareRequestResponse;
}

export function POSOrderPrepareResponseFromJSON(json: any): POSOrderPrepareResponse {
    return POSOrderPrepareResponseFromJSONTyped(json, false);
}

export function POSOrderPrepareResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): POSOrderPrepareResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'client': POSOrderPrepareClientResponseFromJSON(json['client']),
        'request': POSOrderPrepareRequestResponseFromJSON(json['request']),
    };
}

export function POSOrderPrepareResponseToJSON(value?: POSOrderPrepareResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'client': POSOrderPrepareClientResponseToJSON(value.client),
        'request': POSOrderPrepareRequestResponseToJSON(value.request),
    };
}


