/* tslint:disable */
/* eslint-disable */
/**
 * WashMix
 * WashMix REST API
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenRefreshSliding
 */
export interface TokenRefreshSliding {
    /**
     * 
     * @type {string}
     * @memberof TokenRefreshSliding
     */
    token: string;
}

export function TokenRefreshSlidingFromJSON(json: any): TokenRefreshSliding {
    return TokenRefreshSlidingFromJSONTyped(json, false);
}

export function TokenRefreshSlidingFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenRefreshSliding {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function TokenRefreshSlidingToJSON(value?: TokenRefreshSliding | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'token': value.token,
    };
}


