/* tslint:disable */
/* eslint-disable */
/**
 * WashMix
 * WashMix REST API
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenObtainSliding
 */
export interface TokenObtainSliding {
    /**
     * 
     * @type {string}
     * @memberof TokenObtainSliding
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof TokenObtainSliding
     */
    password: string;
}

export function TokenObtainSlidingFromJSON(json: any): TokenObtainSliding {
    return TokenObtainSlidingFromJSONTyped(json, false);
}

export function TokenObtainSlidingFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenObtainSliding {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function TokenObtainSlidingToJSON(value?: TokenObtainSliding | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'password': value.password,
    };
}


