/* tslint:disable */
/* eslint-disable */
/**
 * WashMix
 * WashMix REST API
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WelcomeCheckoutAddress
 */
export interface WelcomeCheckoutAddress {
    /**
     * 
     * @type {number}
     * @memberof WelcomeCheckoutAddress
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof WelcomeCheckoutAddress
     */
    zipCode: string;
    /**
     * 
     * @type {string}
     * @memberof WelcomeCheckoutAddress
     */
    title?: string;
    /**
     * 
     * @type {Date}
     * @memberof WelcomeCheckoutAddress
     */
    readonly created?: Date;
    /**
     * 
     * @type {Date}
     * @memberof WelcomeCheckoutAddress
     */
    readonly changed?: Date;
    /**
     * 
     * @type {string}
     * @memberof WelcomeCheckoutAddress
     */
    addressLine1: string;
    /**
     * 
     * @type {string}
     * @memberof WelcomeCheckoutAddress
     */
    addressLine2?: string;
    /**
     * 
     * @type {string}
     * @memberof WelcomeCheckoutAddress
     */
    instructions?: string;
    /**
     * 
     * @type {boolean}
     * @memberof WelcomeCheckoutAddress
     */
    hasDoorman?: boolean;
}

export function WelcomeCheckoutAddressFromJSON(json: any): WelcomeCheckoutAddress {
    return WelcomeCheckoutAddressFromJSONTyped(json, false);
}

export function WelcomeCheckoutAddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): WelcomeCheckoutAddress {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'zipCode': json['zip_code'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'created': !exists(json, 'created') ? undefined : (new Date(json['created'])),
        'changed': !exists(json, 'changed') ? undefined : (new Date(json['changed'])),
        'addressLine1': json['address_line_1'],
        'addressLine2': !exists(json, 'address_line_2') ? undefined : json['address_line_2'],
        'instructions': !exists(json, 'instructions') ? undefined : json['instructions'],
        'hasDoorman': !exists(json, 'has_doorman') ? undefined : json['has_doorman'],
    };
}

export function WelcomeCheckoutAddressToJSON(value?: WelcomeCheckoutAddress | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'zip_code': value.zipCode,
        'title': value.title,
        'address_line_1': value.addressLine1,
        'address_line_2': value.addressLine2,
        'instructions': value.instructions,
        'has_doorman': value.hasDoorman,
    };
}


